#!/bin/bash
#
#   Ausgabe Logs zu einem Pod
#

export HOME=/var/www

# HTTP Header fuer Client
echo "Content-type: text/html"
echo ""

saveIFS=$IFS
IFS='=&;'
parm=(${QUERY_STRING})
IFS=$saveIFS

cat <<%EOF% 
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Strict//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="shortcut icon" href="https://kubernetes.io/images/favicon.png">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these 
        
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
        integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <style>
    .table-borderless tbody tr td, .table-borderless tbody tr th,
        .table-borderless thead tr th, .table-borderless thead tr td,
        .table-borderless tfoot tr th, .table-borderless tfoot tr td {
        border: none;
    }
    </style>
</head>
<body>
  <h3>Logs: ${parm[1]}</h3>
    <pre>
$(kubectl --kubeconfig ${HOME}/.kube/config logs -n ${parm[0]} ${parm[1]})
    </pre>
  <h3>Details: ${parm[1]}</h3>
    <pre>
$(kubectl --kubeconfig ${HOME}/.kube/config describe -n ${parm[0]} pod/${parm[1]})
    </pre>
</body>
</html>
%EOF%
